### ISSUE TITLE
Sumit Review form not working.

### ISSUE THREAD

**Issue by iGlobalProfits** [geminilabs/site-reviews-v2#2]
I've installed the plugin on my site and it only works when I hide email if I unhide email and try to use the form it doesn't work. the site feel free to try and submit a review at http://www.solarsmartquotes.com

**Comment by pryley** [comment]
Please use the [support forum](https://wordpress.org/support/plugin/site-reviews/) for help with the plugin.

Also, that website does not work.

**Comment by iGlobalProfits** [comment]
Sorry the website is http://www.solarsmartquote.com

Thank you.

**Comment by pryley** [comment]
Github issues are only for problems with the source-code, your issue is likely due to a conflict with the Autoptimize plugin.

Please open a topic in the [support forum](https://wordpress.org/support/plugin/site-reviews/) for help with this.

Thanks
