### ISSUE TITLE
Can I add shortcodes of custom fields email field to the notification receipts?

### ISSUE THREAD

**Issue by ljubacanoa** [geminilabs/site-reviews-v2#5]
Project is Yelp like kind of the site. In other words, every single post is different owner of the page/post. I would like to enable approval by page/post owner as well, but at least to have notification for owners of the page/post. Can it be done?

**Comment by pryley** [comment]
**Please use the forum for support requests:** https://wordpress.org/support/plugin/site-reviews/

To answer your question, it is not really possible at present to send notifications to the assigned post author.

...but it will be in the upcoming v3 of Site Reviews:

<img width="439" alt="settings site-reviews wordpress 2018-08-01 11-44-03" src="https://user-images.githubusercontent.com/134939/43538892-7e291d5e-9580-11e8-8840-165cb11bcab0.png">
